#!/bin/bash

rm *.tokens
rm -rf generated
mkdir generated

java -jar /usr/local/lib/antlr-4.7-complete.jar -o generated DLSLexer.g4
java -jar /usr/local/lib/antlr-4.7-complete.jar -o generated DLSParser.g4

cp generated/*.tokens .

javac generated/*.java

export CLASSPATH="./generated:$CLASSPATH"
java org.antlr.v4.gui.TestRig DLS file -gui test.txt
#java org.antlr.v4.gui.TestRig DLSLexer tokens -tokens test.txt

