#!/bin/bash

java -jar /usr/local/lib/antlr-4.7-complete.jar TestLexer.g4
java -jar /usr/local/lib/antlr-4.7-complete.jar TestParser.g4
javac *.java
java org.antlr.v4.gui.TestRig Test root -tokens test.txt

rm *.java
rm *.class